version: 0.0
os: linux
files:
  - source: /FrontEnd/dist
    destination: //opt/tomcat/webapps/data-validation
  - source: /API/target/API-1.0-SNAPSHOT
    destination: //opt/tomcat/webapps/data-validation
hooks:
  BeforeInstall:
    - location: aws_scripts/cleanup
      timeout: 300
      runas: root
