version: 0.2

phases:
  install:
    commands:
      - apt-get -y update
      - apt-get -y install chromium-codecs-ffmpeg-extra=34.0.1847.116-0ubuntu2
      - apt-get -y install chromium-browser=34.0.1847.116-0ubuntu2
      - export DISPLAY=:0.0
  pre_build:
    commands:
      - IP=$(curl http://checkip.amazonaws.com)/32
      - echo $IP of CodeBuild Instance
  build:
    commands:
      - echo Build started on `date`
      - mvn -B package
  post_build:
    commands:
      - IP=$(curl http://checkip.amazonaws.com)/32
      - echo $IP of CodeBuild Instance
      - echo Build completed on `date`
artifacts:
  files:
    - appspec.yml
    - aws_scripts/**/*
    - API/target/API-1.0-SNAPSHOT/**/*
    - FrontEnd/dist/**/*